In [41]:
a = [None] * 20

In [42]:
a[5] = 0

In [44]:
a[1:2]

[None]

In [50]:
any(a == 0)

TypeError: 'bool' object is not iterable

In [56]:
import os
os.sleep(1)

AttributeError: module 'os' has no attribute 'Sleep'

In [64]:
(np.array(a) == None).any()

True

In [65]:
a=[[1,2,3],1,None]

In [66]:
np.array(a) == None

array([False, False,  True])

In [68]:
a = np.load('test.npy', allow_pickle = True)

In [69]:
a

array([array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       None, None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [85]:
None in a.list()

AttributeError: 'numpy.ndarray' object has no attribute 'list'

In [99]:
if False in [False, False]:
    print('h')

h
